version: '3.7'
services:
    nginx:
        image: cappw/dev:nginx-1.17.6
        container_name: proyectoprueba.nginx
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html/
        links:
            - php
        restart: always
        networks:
            - nuevared
    php:
        build: ./docker/php/
        container_name: proyectoprueba.php-7.2
        expose:
            - 9000
        volumes:
            - ./docker/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
            - .:/var/www/html/
        links:
            - database
        env_file:
            - .env
        restart: always
        networks:
            - nuevared
    database:
        image: mysql
        container_name: proyectoprueba.mysql
        env_file:
            - .env
        volumes:
            - ./docker/database/mysql/:/var/lib/mysql
            - ./sql/usuarios.sql:/docker-entrypoint-initdb.d/1.sql
        ports:
            - "3306:3306"
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        networks:
            nuevared:
networks:
    nuevared: